- job:
    name: packstack-base
    parent: base
    timeout: 7200
    post-run: playbooks/upload-logs.yaml
    irrelevant-files:
      - ^docs/.*$
      - ^releasenotes/.*$
    required-projects:
      - x/packstack
      - openstack/puppet-aodh
      - openstack/puppet-ceilometer
      - openstack/puppet-cinder
      - openstack/puppet-glance
      - openstack/puppet-gnocchi
      - openstack/puppet-heat
      - openstack/puppet-magnum
      - openstack/puppet-horizon
      - openstack/puppet-ironic
      - openstack/puppet-keystone
      - openstack/puppet-manila
      - openstack/puppet-neutron
      - openstack/puppet-nova
      - openstack/puppet-openstack_extras
      - openstack/puppet-openstacklib
      - openstack/puppet-oslo
      - openstack/puppet-ovn
      - openstack/puppet-panko
      - openstack/puppet-sahara
      - openstack/puppet-swift
      - openstack/puppet-tempest
      - openstack/puppet-trove
      - openstack/puppet-vswitch

- job:
    name: packstack-allinone
    parent: packstack-base
    pre-run: playbooks/packstack-pre.yaml
    nodeset:
      nodes:
        - name: allinone
          label: centos-7
    run: playbooks/packstack-integration-tempest.yaml

- job:
    name: packstack-fedora
    parent: packstack-base
    vars:
      # NOTE(jpena) switch this to puppet-passed-ci when available
      delorean: "https://trunk.rdoproject.org/fedora28-stein/consistent/delorean.repo"
      delorean_deps: "https://trunk.rdoproject.org/fedora28-stein/delorean-deps.repo"
      selinux_enforcing: "false"
    pre-run: playbooks/packstack-fedora-pre.yaml
    nodeset:
      nodes:
        - name: fedora
          label: fedora-28
    run: playbooks/packstack-integration-tempest.yaml

- job:
    name: packstack-multinode
    parent: packstack-base
    pre-run: playbooks/packstack-pre.yaml
    nodeset:
      nodes:
        - name: controller
          label: centos-7
        - name: compute
          label: centos-7
    run: playbooks/packstack-multinode.yaml

- job:
    name: packstack-integration-scenario001-tempest
    parent: packstack-allinone
    vars:
      scenario: scenario001

- job:
    name: packstack-integration-scenario002-tempest
    parent: packstack-allinone
    vars:
      scenario: scenario002

- job:
    name: packstack-integration-scenario003-tempest
    parent: packstack-allinone
    vars:
      scenario: scenario003

- job:
    name: packstack-fedora-integration-scenario-py3-tempest
    parent: packstack-fedora
    vars:
      scenario: scenario-py3

# We should have nested post-run jobs, according to
# https://docs.openstack.org/infra/zuul/user/config.html#job
- job:
    name: packstack-multinode-scenario002-tempest
    parent: packstack-multinode
    post-run: playbooks/packstack-post-compute.yaml
    vars:
      scenario: scenario002

- project:
    check:
      jobs:
        - packstack-integration-scenario001-tempest
        - packstack-integration-scenario002-tempest
        - packstack-integration-scenario003-tempest
        - packstack-multinode-scenario002-tempest
        - packstack-fedora-integration-scenario-py3-tempest:
            voting: false
        - openstack-tox-py36:
            voting: false
    gate:
      jobs:
        - packstack-integration-scenario001-tempest
        - packstack-integration-scenario002-tempest
        - packstack-integration-scenario003-tempest
        - packstack-multinode-scenario002-tempest
